const nameOnPass = "David";
console.log("Passenger Name: " + nameOnPass);
const nameOnId = "David";

const nameMatch = nameOnId === nameOnPass;
console.log("ID confirmed? " + nameMatch);
const length = 23;
const doesLengthPass = length < 30;
const height = 24;
const doesHeightPass = height < 55;
const isHandBaggageEligible = doesLengthPass && doesHeightPass;
console.log("Is Hand Baggage Eligible? " + isHandBaggageEligible);
const flightDes = "Porto";
const returnFrom = "Warszawa";
const isRoundTrip = flightDes === returnFrom;
console.log("Round Trip Check? " + isRoundTrip);
const bookings = 4;
const totalCapacity = 5;
const isFlightAvailable = bookings < totalCapacity;
console.log("Are seats available? " + isFlightAvailable);
document.querySelector("#name").innerHTML = nameOnPass;
document.querySelector("#id").innerHTML = nameMatch;
document.querySelector("#bag").innerHTML = isHandBaggageEligible;
document.querySelector("#des").innerHTML = isRoundTrip;
document.querySelector("#seat").innerHTML = isFlightAvailable;